---
- name: OpenShift Health Checks
  hosts: oo_etcd_to_config:oo_nodes_to_config:oo_masters_to_config

  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: pre-install
  post_tasks:
  - name: Run health checks (@preflight)
    action: openshift_health_check
    args:
      checks: ['@preflight']
